### PR TITLE
Install entity type

### PR DESCRIPTION
**Pull request by acouch**
This I think fixes https://github.com/NuCivic/internal/issues/677

There isn't an acceptance test so not sure how to confirm. I assume that installing odsm / dkan with that branch and then visiting `api/action/3/site_read` and the ODSM admin page without error would be an AC.

### CODE REVIEW

**Comment by kducharm** [comment]
Closing, internal repo has been removed so can't reference original issue.

**Comment by acouch** [comment]
This is still off since it should be ``type`` not ``entity``. I don't recall the error it produces https://github.com/NuCivic/open_data_schema_map/blob/7.x-1.x/open_data_schema_map.install#L51

**Comment by janette** [comment]
@acouch I don't see errors on the ODSM admin page and going to `api/action/3/site_read` gives me a 404

Do you recall what the original issue was?

**Comment by kducharm** [comment]
@acouch @janette I've confirmed it's supposed to be `type` and not `entity` from the DB tables, so merging and I could only find the CKAN module using the hook.

**Pull request merged**
